version: '3.5'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    command: 'sh /etc/nginx/start-nginx.sh'
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      # - 80:80
      - 8000:8000
    volumes:
      - ./nginx/logs/nginx/:/var/log/nginx/
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./toram/static:/var/www/static/
      - ./toram/media:/var/www/media/
    depends_on:
      - django

  next.js:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes: ./frontend:/frontend/
    command: yarn dev
    depends_on:
      - backend

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: 'sh /backend/start-django.sh'
    env_file: ./backend/.django_env
    expose:
      - "8001"
    volumes:
      - ./backend:/backend/

  db:
    image: postgres:latest
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file: ./db/.postgres_env
    command: 'postgres -c config_file="/etc/postgresql.conf"'
volumes:
  dbdata:
